import { useEffect, useState } from "react";
import { getMyCertificates } from "../../api/certificate.api";
import toast from "react-hot-toast";

const Certificates = () => {
  const [certificates, setCertificates] = useState([]);
  const [loading, setLoading] = useState(true);

  const fetchCertificates = async () => {
    try {
      setLoading(true);
      const res = await getMyCertificates();
      setCertificates(res.data);
    } catch (error) {
      console.error("Error fetching certificates:", error);
      toast.error("Failed to load certificates");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchCertificates();
  }, []);

  if (loading) {
    return (
      <div className="flex items-center justify-center min-h-[400px]">
        <div className="text-center">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600 mx-auto"></div>
          <p className="mt-4 text-gray-600">Loading certificates...</p>
        </div>
      </div>
    );
  }

  return (
    <div className="p-6">
      {/* ================= HEADER ================= */}
      <div className="mb-6">
        <h1 className="text-3xl font-bold text-gray-900">My Certificates</h1>
        <p className="text-gray-600 mt-1">View and download your achievement certificates</p>
      </div>

      {/* ================= EMPTY STATE ================= */}
      {certificates.length === 0 && (
        <div className="bg-white rounded-lg shadow-md p-12 text-center">
          <div className="text-6xl mb-4">🎓</div>
          <p className="text-gray-500 text-lg mb-2">No certificates yet</p>
          <p className="text-gray-400 text-sm">
            Certificates will appear here once they are generated by teachers after competitions.
          </p>
        </div>
      )}

      {/* ================= CERTIFICATES GRID ================= */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {certificates.map((certificate) => (
          <div
            key={certificate._id}
            className="bg-white rounded-lg shadow-md hover:shadow-lg transition p-6 border border-gray-200"
          >
            <div className="flex items-center justify-between mb-4">
              <div className={`px-3 py-1 rounded-full text-sm font-medium ${
                certificate.type === "winner"
                  ? "bg-yellow-100 text-yellow-700"
                  : "bg-blue-100 text-blue-700"
              }`}>
                {certificate.type === "winner" ? "🏆 Winner" : "📜 Participation"}
              </div>
              {certificate.position && (
                <span className="text-lg font-bold text-gray-700">
                  #{certificate.position}
                </span>
              )}
            </div>

            <h3 className="font-semibold text-lg mb-2">
              {certificate.competition?.name || "Competition"}
            </h3>

            <div className="text-sm text-gray-600 space-y-1 mb-4">
              {certificate.team && (
                <p><strong>Team:</strong> {certificate.team.teamName}</p>
              )}
              <p>
                <strong>Issued:</strong> {new Date(certificate.createdAt).toLocaleDateString()}
              </p>
            </div>

            <a
              href={`http://localhost:5000${certificate.pdfUrl}`}
              target="_blank"
              rel="noopener noreferrer"
              className="block w-full bg-blue-600 hover:bg-blue-700 text-white text-center py-2 rounded-lg font-medium transition"
            >
              📥 Download Certificate
            </a>
          </div>
        ))}
      </div>
    </div>
  );
};

export default Certificates;
